"use client";
import Image from "next/image";
import { useEffect, useState } from "react";

const WHATSAPP="https://wa.me/5561992087470?text=Ol%C3%A1%20Filipe!%20Vi%20seu%20portf%C3%B3lio%20e%20gostaria%20de%20conversar%20sobre%20uma%20oportunidade.";
const LINKEDIN="https://www.linkedin.com/in/filipe-fran%C3%A7a-de-oliveira";
const GITHUB="https://github.com/FilipeFrancadeOliveir";
const EMAIL="mailto:filipi95527646@gmail.com?subject=Contato%20pelo%20portf%C3%B3lio";
const projects=[
 {n:"01",kind:"DESENVOLVIMENTO",title:"Experiências digitais",text:"Interfaces responsivas e aplicações pensadas para funcionar com clareza em qualquer tela.",tags:["React","Next.js","UX"],color:"violet"},
 {n:"02",kind:"DADOS",title:"Informação bem apresentada",text:"Indicadores e visualizações que facilitam a leitura e ajudam pessoas a decidir melhor.",tags:["Power BI","SQL","Storytelling"],color:"lime"},
 {n:"03",kind:"EFICIÊNCIA",title:"Processos mais simples",text:"Tecnologia aplicada para organizar rotinas, reduzir esforço e dar mais fluidez ao trabalho.",tags:["Automação","Análise","Melhoria contínua"],color:"cyan"},
];
const experiences=[
 ["2023 — AGORA","Assistente Administrativo","Centro Corporativo Sicoob · Brasília","Gestão de contratos, despesas, rateios, fornecedores e fluxos financeiros. Transformo rotinas operacionais em processos organizados, indicadores e decisões mais claras."],
 ["2019 — 2023","Técnico de TI · N1/N2","Sicoob Confederação","Suporte, infraestrutura e resolução de incidentes com proximidade dos usuários e visão completa da operação."],
 ["2019","Assistente de Suporte","Hospital Daher","Manutenção de equipamentos, redes e sistemas em ambiente crítico, com foco em disponibilidade e continuidade."],
];
const education=[["MBA","Governança Corporativa, Digital e de Dados","Concluído"],["PÓS","Arquitetura e Projetos de Cloud Computing","Concluído em 2025"],["PÓS","Desenvolvimento Full Stack e Cloud Computing","Concluído em 2025"],["GRADUAÇÃO","Análise e Desenvolvimento de Sistemas","Concluído em 2024"]];

export default function Home(){
 const[menuOpen,setMenuOpen]=useState(false);const[progress,setProgress]=useState(0);const[cursor,setCursor]=useState({x:-100,y:-100});
 useEffect(()=>{const root=document.documentElement;const reduced=matchMedia("(prefers-reduced-motion: reduce)").matches;const onScroll=()=>{const max=root.scrollHeight-innerHeight;setProgress(max?scrollY/max:0);if(!reduced)root.style.setProperty("--scroll",String(scrollY))};const onMove=(e:MouseEvent)=>setCursor({x:e.clientX,y:e.clientY});const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add("is-visible");observer.unobserve(e.target)}}),{threshold:.14,rootMargin:"0px 0px -8%"});document.querySelectorAll("[data-reveal]").forEach(el=>observer.observe(el));addEventListener("scroll",onScroll,{passive:true});addEventListener("mousemove",onMove,{passive:true});onScroll();return()=>{observer.disconnect();removeEventListener("scroll",onScroll);removeEventListener("mousemove",onMove)}},[]);
 return <main>
  <div className="progress" style={{transform:`scaleX(${progress})`}}/><div className="cursor-glow" style={{transform:`translate3d(${cursor.x}px,${cursor.y}px,0)`}} aria-hidden/>
  <header className="nav"><a className="brand" href="#inicio"><b>FF</b><span>Filipe França</span></a><button className="menu" onClick={()=>setMenuOpen(!menuOpen)} aria-expanded={menuOpen}>{menuOpen?"FECHAR":"MENU"}</button><nav className={menuOpen?"open":""}>{[["Sobre","sobre"],["Projetos","projetos"],["Trajetória","trajetoria"],["Formação","formacao"]].map(([l,id])=><a key={id} href={`#${id}`} onClick={()=>setMenuOpen(false)}>{l}</a>)}</nav><a className="nav-cta" href={WHATSAPP} target="_blank" rel="noreferrer">VAMOS CONVERSAR <span>↗</span></a></header>
  <section className="hero" id="inicio"><div className="hero-grid" aria-hidden/><div className="hero-word word-top" aria-hidden>FILIPE</div><div className="hero-word word-bottom" aria-hidden>FRANÇA</div><p className="availability"><i/> BRASÍLIA · DISPONÍVEL PARA NOVOS DESAFIOS</p><div className="hero-copy"><p className="hero-role">DESENVOLVIMENTO · DADOS · CLOUD</p><h1><span>FILIPE</span><span className="outline">FRANÇA</span></h1><p className="hero-statement">Tecnologia com visão prática, repertório técnico e atenção ao que realmente precisa ser resolvido</p><div className="hero-links"><a href="#sobre">CONHEÇA MINHA HISTÓRIA <b>↓</b></a><a href="https://www.linkedin.com/in/filipe-fran%C3%A7a-de-oliveira" target="_blank" rel="noreferrer">LINKEDIN <b>↗</b></a></div></div><div className="portrait-wrap"><div className="portrait-halo"/><div className="portrait-back"/><Image src="/filipe-franca.jpg" alt="Filipe França de Oliveira" width={520} height={650} priority/><span>FULL STACK · CLOUD · DATA</span><div className="portrait-badge"><b>7+</b><small>ANOS DE<br/>EXPERIÊNCIA</small></div></div><div className="scroll-note"><span>SCROLL PARA EXPLORAR</span><i>↓</i></div></section>
  <div className="ticker"><div>{[...Array(2)].flatMap((_,i)=>["ANÁLISE DE DADOS","POWER BI","CLOUD","FULL STACK","INFRAESTRUTURA"].map(x=><span key={i+x}>{x}<i>✦</i></span>))}</div></div>
  <section className="manifest section" id="sobre"><div className="section-label">01 — SOBRE</div><div className="manifest-copy" data-reveal><p className="kicker">PERFIL HÍBRIDO ENTRE CÓDIGO, DADOS E PESSOAS</p><h2>Não quero ser só mais um profissional de tecnologia</h2><p className="manifest-lead">Quero entender o problema inteiro — e construir a solução que realmente muda o jogo.</p></div><div className="manifest-details" data-reveal><p>Minha carreira começou no suporte e na infraestrutura. Foi resolvendo problemas reais, com pessoas reais, que aprendi uma regra simples: tecnologia só é boa quando funciona para quem precisa dela.</p><p>Hoje junto essa base a desenvolvimento Full Stack, arquitetura cloud, governança e análise de dados. Essa visão completa me permite sair do pedido inicial, entender a necessidade por trás dele e entregar algo melhor.</p><div className="metrics"><div><b>01</b><span>VISÃO<br/>SISTÊMICA</span></div><div><b>02</b><span>EXECUÇÃO<br/>PRÁTICA</span></div><div><b>03</b><span>IMPACTO<br/>MENSURÁVEL</span></div></div></div></section>
  <section className="projects section" id="projetos"><div className="section-label">02 — O QUE EU CONSTRUO</div><div className="projects-heading" data-reveal><h2>Soluções que<br/><em>fazem sentido</em></h2><p>Minha atuação conecta tecnologia, informação e operação sem complicar o que pode ser simples</p></div><div className="project-grid">{projects.map(p=><article className={p.color} data-reveal key={p.n}><div><span>{p.n}</span><small>{p.kind}</small></div><h3>{p.title}</h3><p>{p.text}</p><div className="project-tags">{p.tags.map(t=><small key={t}>{t}</small>)}</div><i>↗</i></article>)}</div></section>
  <section className="capabilities section"><div className="section-label">03 — COMO EU ENTREGO</div><div className="cap-head" data-reveal><p>QUATRO PERSPECTIVAS<br/>UMA SOLUÇÃO COMPLETA</p><h2>Do problema<br/>ao <em>resultado</em></h2></div><div className="cap-list">{[["01","DATA","Bases confiáveis, indicadores relevantes e dashboards que contam uma história."],["02","DEV","Interfaces responsivas e aplicações pensadas para pessoas, não só para telas."],["03","CLOUD","Infraestrutura e arquitetura com visão de disponibilidade, escala e segurança."],["04","OPS","Processos, fornecedores e fluxos organizados com foco no que gera valor."]].map(x=><article data-reveal key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p><i>↗</i></article>)}</div></section>
  <section className="journey section" id="trajetoria"><div className="section-label">04 — TRAJETÓRIA</div><div className="journey-title" data-reveal><h2>Experiência que<br/><em>conecta pontos</em></h2><p>Uma carreira construída entre tecnologia, atendimento e operação — sempre entendendo antes de executar.</p></div><div className="timeline">{experiences.map((e,i)=><article data-reveal key={e[1]}><span>0{i+1}</span><time>{e[0]}</time><div><h3>{e[1]}</h3><h4>{e[2]}</h4></div><p>{e[3]}</p></article>)}</div></section>
  <section className="education section" id="formacao"><div className="section-label">05 — FORMAÇÃO</div><div className="education-grid"><div data-reveal><p className="kicker">CONHECIMENTO EM MOVIMENTO</p><h2>Aprender<br/>Aplicar<br/><em>Evoluir</em></h2></div><div className="degree-list">{education.map((e,i)=><article data-reveal key={e[1]}><span>0{i+1}</span><div><small>{e[0]}</small><h3>{e[1]}</h3><p>{e[2]}</p></div><i>↗</i></article>)}</div></div></section>
  <section className="contact section" id="contato"><div className="contact-rings"><i/><i/><i/></div><p className="kicker">TEM UM DESAFIO INTERESSANTE?</p><h2 data-reveal>Vamos construir<br/><em>algo relevante</em></h2><div className="contact-actions" data-reveal><a href={WHATSAPP} target="_blank" rel="noreferrer">WHATSAPP <span>↗</span></a><a href={LINKEDIN} target="_blank" rel="noreferrer">LINKEDIN <span>↗</span></a><a href={GITHUB} target="_blank" rel="noreferrer">GITHUB <span>↗</span></a><a href={EMAIL}>E-MAIL <span>↗</span></a></div></section>
  <footer><a className="brand" href="#inicio"><b>FF</b><span>Filipe França</span></a><p>BRASÍLIA · DF<br/>© 2026</p><p>DESENVOLVIDO COM<br/>INTENÇÃO E CÓDIGO.</p></footer>
 </main>
}
